services:
  - type: web
    name: vive-descubre-pabellon
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        headers:
          X-Frame-Options: DENY
          X-Content-Type-Options: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html